const container = document.querySelector(".carousel");
const colorMenu = document.querySelector(".menu");

const computerParts = [
  "Computer Case",
  "MOBO",
  "CPU",
  "GPU",
  "Monitor",
  "Keyboard",
  "Mouse",
  "RAM",
  "Printer",
  "Camera"
];
const themeColors = [
  "#8360C3-#2EBF91",
  "#FC5C7D-#6A82FB",
  "#FF512F-#F09819",
  "#5A3F37-#2C7744",
  "#9796F0-#FBC7D4",
];

computerParts.forEach((part) => {
  container.innerHTML += `
  <div class='card'>
    <div class='card_inner'>
      <div class='card_face card_face-front'>
        <h2>${part}</h2>
        <img class='face-image' src='images/${part}.jpg' alt='' draggable='false' />
      </div>
      <div class='card_face card_face-back'>
        <div class='card_content'>
          <div class='card_header'>
            <img class='header-image'src='images/${part}.jpg' alt='' draggable='false' />
            <input readonly class="h2" value= "${getName(part)}">
          </div>
          <div class='card_body'>
            <textarea readonly placeholder="Insert Description" class='text-info' type='text'>${getInfo(part)}</textarea>
            <i class='fa-solid fa-pen editBtns'></i>
            <i class='fa-solid fa-floppy-disk editBtns'></i>
          </div>
        </div>
      </div>
    </div>
  </div>
  `;
});

themeColors.forEach((theme, themeIndex) => {
  let colors = theme.split("-");
  colorMenu.innerHTML += `
    <li>
      ${colors[0]}-${colors[1]}
      <div class="colorbox"></div>
    </li>
    `;
  const colorBoxes = document.querySelectorAll("li .colorbox");
  colorBoxes[themeIndex].style.borderLeft = `10px solid ${colors[0]}`;
  colorBoxes[themeIndex].style.borderTop = `10px solid ${colors[0]}`;
  colorBoxes[themeIndex].style.borderBottom = `10px solid ${colors[1]}`;
  colorBoxes[themeIndex].style.borderRight = `10px solid ${colors[1]}`;
});

function getName(abbrev) {
  switch (abbrev) {
    case "CPU":
      return "Central Processing Unit";
    case "GPU":
      return "Graphics Processing Unit";
    case "MOBO":
      return "Motherboard";
    case "RAM":
      return "Random Access Memory";
    default:
      return abbrev;
  }
}

function getInfo(abbrev) {
  switch (abbrev) {
    case "CPU":
      return "The CPU is the brain of a computer, containing all the circuitry needed to process input, store data, and output results.";
    case "Computer Case":
      return "A computer case, also known as a computer chassis, is the enclosure that contains most of the hardware of a personal computer.";
    case "MOBO":
      return "A motherboard is the main printed circuit board (PCB) in a computer. The motherboard is a computer's central communications backbone connectivity point, through which all components and external peripherals connect.";
    case "GPU":
      return "A specialized processor originally designed to accelerate graphics rendering. GPUs can process many pieces of data simultaneously, making them useful for machine learning, video editing, and gaming applications.";
    case "Monitor":
      return "A monitor is an electronic output device used to display information being entered and processed on a computer. The primary use of a monitor is to display images, text, video, and graphics information generated by the computer via a computer's video card.";
    case "Keyboard":
    return "A computer keyboard is an input device used to enter characters and functions into the computer system by pressing buttons, or keys. It is the primary device used to enter text.";
    case "mouse":
      return "A computer mouse (plural mice, also mouses) is a hand-held pointing device that detects two-dimensional motion relative to a surface. This motion is typically translated into the motion of the pointer (called a cursor) on a display, which allows a smooth control of the graphical user interface of a computer.";    
    case "RAM":
      return "RAM is a common computing acronym that stands for random-access memory. Sometimes it's called PC memory or just memory. In essence, RAM is your computer or laptop's short-term memory. It's where the data is stored that your computer processor needs to run your applications and open your files.";
    case "Camera":
      return "A webcam is a digital camera that captures video and audio data and transmits it in real-time over the internet. It is commonly used for video conferencing, live streaming, online meetings, and recording videos."    
    case "Printer":
      return "A printer is a device that prints documents and images onto paper or other materials. It is usually connected to a computer, allowing you to use your word processor, spreadsheets, and other programs to create documents and images that are printed out on the printer."
      default:
      return "";
  }
}
